add_newline = false

[username]
# show_always = true
style_root = "red"
style_user = "purple"

[hostname]
# ssh_only = false
style = "yellow"

[directory]
style = "green"
truncation_length = 5

[cmd_duration]
style = "yellow"
min_time = 5_000

[git_state]
style = "yellow"

[git_status]
format = '([\[$conflicted[$deleted](yellow)[$renamed](bright-red)[$modified](red)[$staged](green)[$untracked](purple)$ahead_behind\]]($style) )'
style = "bright-yellow"
stashed = ""
modified = "●"
staged = "●"
untracked = "●"
deleted = "●"
renamed = "●"

[jobs]
style = "blue"

[aws]
symbol = " "
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "
disabled = true

[git_branch]
symbol = " "
style = "cyan"

[golang]
symbol = " "
disabled = true

[hg_branch]
symbol = " "

[java]
symbol = " "
disabled = true

[memory_usage]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "

[php]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[nix_shell]
symbol = " "

# [custom.mutagen]
# # when = "rg -c -g '**/*.yml' x-mutagen"
# files = ["docker-compose.yml"]
# command = "mutagen sync list --label-selector 'io.mutagen.compose.project.name == app'"
# disabled = false
